export const CART_ADD_PRODUCT_REQUEST = 'CART_ADD_PRODUCT_REQUEST';
export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS';
export const CART_ADD_PRODUCT_FAIL = 'CART_ADD_PRODUCT_FAIL';
export const CART_REMOVE_PRODUCT_SUCCESS = 'CART_REMOVE_PRODUCT_SUCCESS';
export const CART_REMOVE_ALL_PRODUCTS = 'CART_REMOVE_ALL_PRODUCTS';
